sources:
  - name: cloud_sql_postgresql
    description: "Source data from Cloud SQL PostgreSQL"
    schema: public
    meta:
      external_location: "postgresql://{{ env_var('CLOUDSQL_USER') }}:{{ env_var('CLOUDSQL_PASSWORD') }}@{{ env_var('CLOUDSQL_HOST') }}:{{ env_var('CLOUDSQL_PORT') }}/{{ env_var('CLOUDSQL_DATABASE') }}"
    tables:
      - name: orders
        description: "Orders table"
        external:
          location: "SELECT * FROM public.orders"
          options:
            format: 'POSTGRESQL'
            
      - name: order_items
        description: "Order items table"
        external:
          location: "SELECT * FROM public.order_items"
          options:
            format: 'POSTGRESQL'
            
      - name: customers
        external:
          location: "SELECT * FROM public.customers"
          
      - name: products
        external:
          location: "SELECT * FROM public.products"
          
      - name: product_category_name_translation
        external:
          location: "SELECT * FROM public.product_category_name_translation"
          
      - name: payments
        external:
          location: "SELECT * FROM public.payments"
          
      - name: reviews
        external:
          location: "SELECT * FROM public.reviews"
          
      - name: sellers
        external:
          location: "SELECT * FROM public.sellers"
          
      - name: geolocation
        external:
          location: "SELECT * FROM public.geolocation"