sources:
  - name: raw_data
    description: "Source data from Cloud SQL PostgreSQL"
    schema: airbyte_schema
    database: airbyte_database
    tables:
      - name: orders
        description: "Orders table"
          
      - name: order_items
        description: "Order items table"

      - name: customers
        description: "Customers table"

      - name: products
        description: "Products table"

      - name: product_category_name_translation
        description: "Product category translations"

      - name: payments
        description: "Order payments table"

      - name: reviews
        description: "Order reviews table"

      - name: sellers
        description: "Sellers table"
        
      - name: geolocation
        description: "Geolocation data for sellers"