version: '3'

services:

  dagster-daemon:
    build: ./dagster
    command: dagster-daemon run
    volumes:
      - ./dagster:/opt/dagster/app
    env_file: .env


  dagster-dagit:
    build: ./dagster
    ports:
      - "3000:3000"
    volumes:
      - ./dagster:/opt/dagster/app
    env_file: .env
    depends_on:
      - dagster-daemon


  dbt:
    build: ./dbt
    volumes:
      - ./dbt:/dbt
    env_file: .env
    depends_on:
      - dagster-dagit
