version: '3'

services:

  dagster-daemon:
    build: ./dagster
    command: dagster-daemon run
    volumes:
      - ./dagster:/opt/dagster/app
    env_file: .env


  dagster-dagit:
    build: ./dagster
    ports:
      - "3000:3000"
    volumes:
      - ./dagster:/opt/dagster/app
    env_file: .env
    depends_on:
      - dagster-daemon


  dbt:
    build: ./dbt
    volumes:
      - ./dbt:/dbt
    env_file: .env
    depends_on:
      - dagster-dagit


  # Base de données pour Superset
  superset-db:
    image: postgres:14
    container_name: superset-postgres
    env_file: .env
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "admin"]
      interval: 5s
      retries: 5

  # Service Superset principal
  superset:
    build: 
      context: ./superset
      dockerfile: Dockerfile
    depends_on:
      superset-db:
        condition: service_healthy
    ports:
      - "8088:8088"
    volumes:
      - ./superset:/app/superset_config
    env_file: .env
    environment:
      - DATABASE_URL=postgresql://superset:superset@superset-db:5432/superset
      - FLASK_APP=superset.app:create_app()