services:
  superset:
    image: apache/superset:latest
    container_name: superset_app
    env_file: .env
    environment:
      - SQLALCHEMY_DATABASE_URI=postgresql+psycopg2://superset:superset@db:5432/superset
      - REDIS_HOST=redis
    ports:
      - "8088:8088"
    depends_on:
      - db
    volumes:
      - superset_home:/app/superset_home
      - ./init.sh:/app/init.sh
    command: ["/bin/sh", "/app/init.sh"]

  db:
    image: postgres:13
    container_name: superset_db
    restart: always
    environment:
      POSTGRES_DB: superset
      POSTGRES_USER: superset
      POSTGRES_PASSWORD: superset
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
  superset_home:
